In [131]:
import numpy as np
import pandas as pd

import itertools
from scipy.spatial.distance import pdist

In [84]:
data1 = np.array([
    [1, 1],
    [1.5, 2],
    [3, 3],
    [5, 7],
    [3.5, 5]
])

In [138]:
def kMeans(data, k=2, maxIteration=100, epsilon=0.0001, randomCentroid=False):
    
    #select centroids
    if randomCentroid:
        minC = np.min(data)
        maxC = np.max(data)
        centroids = np.zeros( (k, data.shape[1]) )
        for i in range(len(centroids)):
            centroids[i] = np.random.uniform(low=minC, high=maxC, size=(data.shape[1],))
    else:
        Npoints = k
        c = [list(x) for x in itertools.combinations(range(len(data)), Npoints )]
        distances = []
        for i in c:    
            distances.append(np.mean(pdist(data[i,:]))) # pdist: a method of computing all pairwise Euclidean distances in a condensed way.

        ind = distances.index(max(distances)) # finding the index of the max mean distance
        rows = c[ind] # these are the points in question
        centroids = data[rows]
    print(centroids)
    
    for epoch in range(maxIteration):        
        #iterattion of k-means
        clusterList = np.zeros(len(data))
        for iRow, row in enumerate(data):
            minDist = np.inf
            cluster = 0
            for i,centroid in enumerate(centroids):
                dist = np.linalg.norm(row-centroid)
                if dist < minDist:
                    minDist = dist
                    cluster = i
            clusterList[iRow] = cluster
            
        #calc new centroids
        clusterList = np.array(clusterList)
        doBreak = True
        for i in range(len(centroids)):
            newValue  = np.mean(data[clusterList==i], axis=0)                   
            if (clusterList==i).any():
              #  print(f"data[clusterList==i] {data[clusterList==i]}")
              #  print(f"newValue: {newValue}")
                if (np.abs(newValue - centroids[i]) > epsilon).any():
                    doBreak = False
                centroids[i] = newValue
        if doBreak:
            print("Change smaller than epsilon: break")
            break
    print(f"Performed {epoch} iteration of kMeans")
    return clusterList, centroids
         
            
        

In [139]:
kMeans(data1)

[[1. 1.]
 [5. 7.]]
Change smaller than epsilon: break
Performed 1 iteration of kMeans


(array([0., 0., 0., 1., 1.]), array([[1.83333333, 2.        ],
        [4.25      , 6.        ]]))

In [140]:
data = pd.read_csv("cereal.csv")

data = data.drop(columns=["name", "mfr", "type"])
data.head()

calories  protein  fat  sodium  fiber  carbo  sugars  potass  vitamins  \
0        70        4    1     130   10.0    5.0       6     280        25   
1       120        3    5      15    2.0    8.0       8     135         0   
2        70        4    1     260    9.0    7.0       5     320        25   
3        50        4    0     140   14.0    8.0       0     330        25   
4       110        2    2     200    1.0   14.0       8      -1        25   

   shelf  weight  cups     rating  
0      3     1.0  0.33  68.402973  
1      3     1.0  1.00  33.983679  
2      3     1.0  0.33  59.425505  
3      3     1.0  0.50  93.704912  
4      3     1.0  0.75  34.384843

In [141]:
x = data.to_numpy()

In [143]:
kMeans(x, k=3)

[[ 50.         4.         0.       140.        14.         8.
    0.       330.        25.         3.         1.         0.5
   93.704912]
 [100.         3.         0.       320.         1.        20.
    3.        45.       100.         3.         1.         1.
   41.50354 ]
 [ 50.         1.         0.         0.         0.        13.
    0.        15.         0.         3.         0.5        1.
   60.756112]]
Change smaller than epsilon: break
Performed 4 iteration of kMeans


(array([0., 2., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        2., 1., 0., 2., 1., 1., 1., 1., 1., 2., 0., 0., 1., 2., 1., 1., 1.,
        2., 1., 1., 1., 1., 1., 1., 1., 1., 2., 0., 0., 0., 1., 1., 1., 1.,
        1., 0., 1., 2., 2., 1., 2., 0., 0., 2., 1., 1., 2., 2., 2., 2., 1.,
        2., 1., 0., 1., 1., 1., 1., 1., 1.]),
 array([[112.14285714,   3.35714286,   1.42857143, 172.5       ,
           5.60714286,  12.03571429,   9.14285714, 217.14285714,
          30.35714286,   2.92857143,   1.16      ,   0.66142857,
          46.01531921],
        [109.78723404,   2.29787234,   0.9787234 , 201.91489362,
           1.22340426,  15.81914894,   7.04255319,  65.93617021,
          32.9787234 ,   2.06382979,   1.02574468,   0.86574468,
          37.79694366],
        [ 93.75      ,   2.5625    ,   0.75      ,  24.375     ,
           1.85625   ,  13.25      ,   4.625     ,  78.6875    ,
          12.5       ,   2.        ,   0.926875  ,   0.829375  ,
          54.0367

In [81]:
x.shape

(77, 13)

False

In [92]:
x = np.array([1,2])
y = np.array([1,5])

In [93]:
np.linalg.norm(x-y)

3.0

In [132]:
Npoints = 3
# making up some data:
data = x
# finding row indices of all combinations:
c = [list(x) for x in itertools.combinations(range(len(data)), Npoints )]

distances = []
for i in c:    
    distances.append(np.mean(pdist(data[i,:]))) # pdist: a method of computing all pairwise Euclidean distances in a condensed way.

ind = distances.index(max(distances)) # finding the index of the max mean distance
rows = c[ind] # these are the points in question

In [133]:
rows

[3, 53, 54]